cd ~/git/redballoon/CoreApi
git up
cd ~/git/redballoon/ECommerceUI
git up
cd ~/git/redballoon/AlfredUI
git up
cd ~/git/redballoon/Gestalt
git up
cd ~/git/redballoon/Legacy-Task
git up
cd ~/git/redballoon/LiveAvailabilityAPI
git up
cd ~/git/redballoon/LiveAvailabilityDomain
git up
cd ~/git/redballoon/LiveAvailabilitySlickDao
git up
cd ~/git/redballoon/SupplierUI
git up
cd ~/git/redballoon/morpheus-web
git up
